export const INIT_FAVORITE_LIST = 'INIT_FAVORITE_LIST';
export const ADD_BOOK_TO_FAVORITE_LIST = 'ADD_BOOK_TO_FAVORITE_LIST';
export const REMOVE_BOOK_FROM_FAVORITE_LIST = 'REMOVE_BOOK_FROM_FAVORITE_LIST';
